#include<stdio.h>
#include<ctype.h>
#include<string.h>
char letras[5],ordenado[5],ordenadoN[5];
int i,j;
char a1;
int main()
	{
		printf("Ingresa cinco letras:\n");
		fflush(stdin);
		gets(letras);
       	if(letras[5]>=6)
      		{
      			printf("Solo se permiten 5 letras");
			}
		else
			{
				strupr(letras);
				strcpy(ordenado,letras);
				//ordenamiento de la ñ :(
				for(i=0;i<5;i++)
					{
						if(ordenado[i]=='A')
						{
							ordenadoN[i]='1';
						}
						else
						{
							if(ordenado[i]=='B')
							{
								ordenadoN[i]='2';
							}
							else
							{
								if(ordenado[i]=='C')
								{
									ordenadoN[i]='3';
								}
								else
								{
									if(ordenado[i]=='D')
									{
										ordenadoN[i]='4';
									}
									else
									{
										if(ordenado[i]=='E')
										{
											ordenadoN[i]='5';
										}
										else
										{
											if(ordenado[i]=='F')
											{
												ordenadoN[i]='6';
											}
											else
											{
												if(ordenado[i]=='G')
												{
													ordenadoN[i]='7';
												}
												else
												{
													if(ordenado[i]=='H')
													{
														ordenadoN[i]='8';
													}
													else
													{
														if(ordenado[i]=='I')
														{
															ordenadoN[i]='9';
														}
														else
														{
															if(ordenado[i]=='J')
															{
																ordenadoN[i]='10';
															}
															else
															{
																if(ordenado[i]=='K')
																{
																	ordenadoN[i]='11';
																}
																else
																{
																	if(ordenado[i]=='L')
																	{
																		ordenadoN[i]='12';
																	}
																	else
																	{
																		if(ordenado[i]=='M')
																		{
																			ordenadoN[i]='13';
																		}
																		else
																		{
																			if(ordenado[i]=='N')
																			{
																				ordenadoN[i]='14';
																			}
																			else
																			{
																				if(ordenado[i]=='Ñ')
																				{
																					ordenadoN[i]='15';
																				}
																				else
																				{
																					if(ordenado[i]=='O')
																					{
																						ordenadoN[i]='16';
																					}
																					else
																					{
																						if(ordenado[i]=='P')
																						{
																							ordenadoN[i]='17';
																						}
																						else
																						{
																							if(ordenado[i]=='Q')
																							{
																								ordenadoN[i]='18';
																							}
																							else
																							{
																								if(ordenado[i]=='R')
																								{
																									ordenadoN[i]='19';
																								}
																								else
																								{
																									if(ordenado[i]=='S')
																									{
																										ordenadoN[i]='20';
																									}
																									else
																									{
																										if(ordenado[i]=='T')
																										{
																											ordenadoN[i]='21';
																										}
																										else
																										{
																											if(ordenado[i]=='U')
																											{
																												ordenadoN[i]='22';
																											}
																											else 
																											{
																												if(ordenado[i]=='V')
																												{
																													ordenadoN[i]='23';
																												}
																												else
																												{
																													if(ordenado[i]=='W')
																													{
																														ordenadoN[i]='24';
																													}
																													else
																													{
																														if(ordenado[i]=='X')
																														{					
																															ordenadoN[i]='25';
																														}
																														else
																														{
																															if(ordenado[i]=='Y')
																															{
																																ordenadoN[i]='26';
																															}
																															else
																															{
																																if(ordenado[i]=='Z')
																																{
																																	ordenadoN[i]='27';
																																}
																																else
																																{
																																	ordenadoN[i]='0';
																																}	
																															}	
																														}
																													}	
																												}
																											}
																										}
																									}		
																								}
																							}	
																						}	
																					}
																				}
																			}
																		}
																	}		
																}	
															}	
														}
													}	
												}	
											}	
										}																					
									}
								}
							}
						}	
					}
				printf("%S",ordenado);
				getchar();
   				getchar();
    		return 0;
			}
	}
				/*for(i=1;i<5;i++)//ordenamiento
                	{
					for(j=0;j<5-i;j++)
						{
							if((ordenadoN[j])>(ordenadoN[j+1]))
                                {
                 					a1=ordenadoN[j];
                 					ordenadoN[j]=ordenadoN[j+1];
                 					ordenadoN[j+1]=a1;
                 				}
                   		}	
					}
				for(i=0;ordenadoN[i];i++)
					{
						if(ordenadoN[i]=='1')
							{
								ordenado[i]='A';
							}
						else
						 	{
						 		if(ordenadoN[i]=='2')
						 			{
						 				ordenado[i]='B';
						 			}
						 	}
						if(ordenadoN[i]=='3')
							{
								ordenado[i]='C';
							}
						else
						 	{
						 		if(ordenadoN[i]=='4')
						 			{
						 				ordenado[i]='D';
						 			}
						 	}
						if(ordenadoN[i]=='5')
							{
								ordenado[i]='E';
							}
						else
						 	{
						 		if(ordenadoN[i]=='6')
						 			{
						 				ordenado[i]='F';
						 			}
						 	}
						if(ordenadoN[i]=='7')
							{
								ordenado[i]='G';
							}
						else
						 	{
						 		if(ordenadoN[i]=='8')
						 			{
						 				ordenado[i]='H';
						 			}
						 	}
						if(ordenadoN[i]=='9')
							{
								ordenado[i]='I';
							}
						else
						 	{
						 		if(ordenadoN[i]=='10')
						 			{
						 				ordenado[i]='J';
						 			}
						 	}
						if(ordenadoN[i]=='11')
							{
								ordenado[i]='K';
							}
						else
						 	{
						 		if(ordenadoN[i]=='12')
						 			{
						 				ordenado[i]='L';
						 			}
						 	}
						if(ordenadoN[i]=='13')
							{
								ordenado[i]='M';
							}
						else
						 	{
						 		if(ordenadoN[i]=='14')
						 			{
						 				ordenado[i]='N';
						 			}
						 	}
						if(ordenadoN[i]=='15')
							{
								ordenado[i]='Ñ';
							}
						else
						 	{
						 		if(ordenadoN[i]=='16')
						 			{
						 				ordenado[i]='O';
						 			}
						 	}
						if(ordenadoN[i]=='17')
							{
								ordenado[i]='P';
							}
						else
						 	{
						 		if(ordenadoN[i]=='18')
						 			{
						 				ordenado[i]='Q';
						 			}
						 	}
						if(ordenadoN[i]=='19')
							{
								ordenado[i]='R';
							}
						else
						 	{
						 		if(ordenadoN[i]=='20')
						 			{
						 				ordenado[i]='S';
						 			}
						 	}
						if(ordenadoN[i]=='21')
							{
								ordenado[i]='T';
							}
						else
						 	{
						 		if(ordenadoN[i]=='22')
						 			{
						 				ordenado[i]='U';
						 			}
						 	}
						if(ordenadoN[i]=='23')
							{
								ordenado[i]='V';
							}
						else
						 	{
						 		if(ordenadoN[i]=='24')
						 			{
						 				ordenado[i]='W';
						 			}
						 	}
						if(ordenadoN[i]=='25')
							{
								ordenado[i]='X';
							}
						else
						 	{
						 		if(ordenadoN[i]=='26')
						 			{
						 				ordenado[i]='Y';
						 			}
						 	}
						if(ordenadoN[i]=='27')
							{
								ordenado[i]='Z';
							}
						else
						 	{
						 		ordenado[i]='0';
						 	}
					}//lave del segundo for
				printf("Tus letras ordenadas son: %s\n",ordenado);
			}*/
    	
	

